config/routes.rb
ScoreTracker::Application.routes.draw do

  root to: 'users#index' # TODO: change this once we have a real home page

  resource :user, only: [ :edit, :update ]
  resources :users, only: [ :index, :show ]
  resources :teams

  match '/signout', to: 'sessions#destroy', via: :delete

  match "/auth/google_oauth2/callback" => "google_sessions#login"
  match "/auth/failure" => "google_sessions#error"
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessor :user1_email, :user2_email
  attr_accessible :user1_email, :user2_email, :name


  validates_presence_of :user1_id, message: "doesn't seem to exist"
  validates_presence_of :user2_id, message: "doesn't seem to exist"

  belongs_to :player1, foreign_key: :user1_id, class_name: 'User'
  belongs_to :player2, foreign_key: :user2_id, class_name: 'User'

  before_validation :set_player_ids

  def name
    db_name = read_attribute(:name)
    db_name.present? ? db_name : "Boring Team Name #{self.id}"
  end

  private

  def set_player_ids
    self.player1 = User.find_by_email(user1_email) if user1_email.present?
    self.player2 = User.find_by_email(user2_email) if user1_email.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :email, :tagline

   valid_email_regex = /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i                                                                                                              

   validates_presence_of :first_name
   validates :email, presence: true, :uniqueness => { :case_sensitive => false }, format: { with: valid_email_regex }

  validates_length_of :tagline, maximum: 128

  before_save :create_remember_token

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/google_sessions_controller.rb
class GoogleSessionsController < ApplicationController

  def login
    auth = request.env['omniauth.auth']

    user = User.find_by_email(auth.info['email']) || User.new

    user.google_id    = auth['uid']
    user.email        = auth.info['email']
    user.first_name   = auth.info['first_name']
    user.last_name    = auth.info['last_name']
    user.google_image_url = auth.info['image']
    user.google_hd    = auth.extra.raw_info['hd']
    user.google_token = auth.credentials['token']

    user.save!

    sign_in user

    redirect_to request.env['omniauth.origin'] || root_url
  end

  def error
    flash[:error] =  "Sorry, something went wrong with the login."
    redirect_to request.env['omniauth.origin'] || root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  before_filter :signed_in_user, except: [ :show ]

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(params[:team])

    if @team.save
      flash[:success] = "Your team has been created."
      redirect_to team_path(@team)
    else
      render :new
    end
  end

  def show
    @team = Team.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in_user, only: :edit

  def index
  end

  def edit
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title page_title
    base_title = "Score Tracker"
    if page_title.blank?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    head :unauthorized unless signed_in?
  end

  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title=title(yield(:title))
    =stylesheet_link_tag    "application", media: "all"
    =javascript_include_tag "application"
    =csrf_meta_tags
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  %body
    %header.navbar.navbar-fixed-top.navbar-inverse
      .navbar-inner
        .container
          =link_to "Score Tracker", '#', class: "brand"
          %nav
            %ul.nav.pull-right
              - if signed_in?
                %li=link_to "New Team", new_team_path
              %li=link_to "Home",     root_path
              %li= link_to "Help",    '#'
              - if signed_in?
                %li#fat-menu.dropdown
                  %a{href: '#', :'data-toggle' => "dropdown", class: "dropdown-toggle" }
                    = current_user.first_name.capitalize
                    %b.caret
                  %ul.dropdown-menu
                    %li= link_to "Profile", user_path(current_user)
                    %li= link_to "Settings", edit_user_path
                    %li.divider
                    %li= link_to "Sign out", signout_path, method: "delete"
              - else
                %li#fat-menu.dropdown
                  %a{href: '#', :'data-toggle' => "dropdown", class: "dropdown-toggle" }
                    Sign in
                    %b.caret
                  %ul.dropdown-menu
                    %a{href: 'auth/google_oauth2'}
                      %li.google-icon.image-rounded
    .container
      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}")
      = yield

app/views/shared/_form_error_messages.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      = "Oops! There's #{pluralize(object.errors.count, "error")}."
    %ul
      - object.errors.full_messages.each do |msg|
        %li.text-error=msg

app/views/users/edit.haml
= provide(:title, "Edit User")

app/views/users/index.haml
= provide(:title, "Home")

app/views/users/show.haml
= provide(:title, "User Profile")